# Generated by Django 3.0.3 on 2020-12-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('answer', models.BooleanField(null=True)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
