# Generated by Django 3.0.3 on 2020-12-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationdb',
            name='answer',
            field=models.CharField(max_length=4),
        ),
    ]
